### ISSUE TITLE
Damage Decreased

### ISSUE THREAD

**Issue by catqueen0124** [Lanboost/TModLoader_LansAutoSummon#2]
Unsure of if this mod is still being updated, but damage of the minions that are autosummoned is reduced down to the base damage, possibly below it. Tested using both modded and vanilla summons, issue occurred with both. Attached is the modpack used when this issue was discovered.

[Server1.zip](https://github.com/Lanboost/TModLoader_LansAutoSummon/files/6047518/Server1.zip)

**Comment by Lanboost** [comment]
The damage should work correctly as the damage is based on the item used to spawn them.

Is there a special minion you have identified this issue with? And do you get different damage based on if the minion is auto-summoned or summoned by hand?

(Also it has been updated now so closing this issue as it might not still be relevant in the first place)

If the issue persist please reopen this or a new issue

Regards
Lan
