### ISSUE TITLE
Sentry De-Summoning

### ISSUE THREAD

**Issue by zauberparacelsus** [Lanboost/TModLoader_LansAutoSummon#5]
So, with the automatic sentry summoning added relatively recently, it seems that the code which desummons and resummons the sentries to make them "follow" you is running when you haven't assigned any sentries to an auto-summon slot, so it is causing manually-summoned sentries to be de-summoned when you move around.

**Comment by Lanboost** [comment]
Should now work correctly as of version V. 2023.10.06.2

**Comment by Lanboost** [comment]
I lied, fixed similar bug but only when needed to resummon minions. As of V. 2023.10.06.3 it should handle the case you are describing
